/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFaceControls, useGLTF } from "@react-three/drei";
import { useControls } from 'leva'
import HolographicMaterial from "./HolographicMaterial";

export function Face2(props) {
  const { nodes, materials } = useGLTF("/faceDeriqTexturepaint.glb");

  const holographicControls = useControls({
    fresnelAmount: { value: 1.00, min: 0.0, max: 1.0 },
    fresnelOpacity: { value: 0.67, min: 0.0, max: 1.0 },
    scanlineSize: { value: 0.1, min: 0.1, max: 20 },
    hologramBrightness: { value: 1.3, min: 0.0, max: 2 },
    signalSpeed: { value: 0.39, min: 0.0, max: 2 },
    hologramColor: { value: "#51a4de" },
    enableBlinking: false,
    blinkFresnelOnly: true,
    enableAdditive: false,
    side: { options: ["FrontSide", "BackSide", "DoubleSide"] },
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FaceBuilderHead.geometry}
       
      >
        <HolographicMaterial {...holographicControls} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/faceDeriqTexturepaint.glb");
